---
- name: Test pull from Secret Server by ID
  hosts: localhost
  gather_facts: false
  vars:
    tss_id: 2
    # Map the injected vars from your custom credential type:
    tss_base_url: "{{ delinea_tss_url | trim }}" 
    tss_username: "{{ delinea_tss_user | trim }}"
    tss_password: "{{ delinea_tss_pass | trim }}"

  tasks:
    - name: Fetch secret JSON via lookup (ID=2)
      set_fact:
        tss_secret: >-
          {{
            lookup(
              'community.general.tss',
              tss_id,
              base_url=tss_base_url,
              username=tss_username,
              password=tss_password
            )
          }}

    # Example: pull the "password" field value
    - name: Show password field from items
      debug:
        msg: >-
          {{
            (tss_secret['items']
              | items2dict(key_name='slug', value_name='itemValue'))['password']
          }}

    - name: Dump entire secret (for troubleshooting)
      debug:
        var: tss_secret
