---
- name: Fetch a Delinea secret by ID using lookup
  hosts: localhost
  gather_facts: false
  
  vars:
    tss_base_url: "{{ delinea_tss_url }}"
    tss_username: "{{ delinea_tss_user }}"
    tss_password: "{{ delinea_tss_pass }}"
    tss_id: 2

  tasks:
    - name: Get secret JSON via lookup
      set_fact:
        tss_secret: >-
          {{
            lookup(
              'community.general.tss',
              tss_id,
              base_url=tss_base_url,
              username=tss_username,
              password=tss_password
            )
          }}

    # Example: extract the "password" field (if present) and show only that value
    - name: Show just the password item (if present)
      vars:
        items_by_slug: >-
          {{ (tss_secret.items | default([]))
             | items2dict(key_name='slug', value_name='itemValue') }}
      debug:
        msg: "{{ items_by_slug.password | default('no password item found') }}"
