- name: Fetch a Delinea secret by ID via REST
  hosts: localhost
  gather_facts: false
  vars:
    base_url: "{{ delinea_tss_url | trim }}"
    username: "{{ delinea_tss_user | trim }}"
    password: "{{ delinea_tss_pass | trim }}"
    secret_id: 2

  tasks:
    - name: Get OAuth token
      uri:
        url: "{{ base_url }}/oauth2/token"
        method: POST
        body_format: form-urlencoded
        body:
          grant_type: password
          username: "{{ username }}"
          password: "{{ password }}"
        validate_certs: false
        return_content: true
      register: token_resp

    - name: Extract token
      set_fact:
        access_token: "{{ token_resp.json.access_token | default(token_resp.json.token) | default('') }}"

    - name: Fail if no token
      fail:
        msg: "No access token returned."
      when: access_token == ''

    - name: Fetch secret by ID (correct /api/v1 path)
      uri:
        url: "{{ base_url }}/api/v1/secrets/{{ secret_id }}"
        method: GET
        headers:
          Authorization: "Bearer {{ access_token }}"
          Accept: "application/json"
        validate_certs: false
        return_content: true
        status_code: [200, 400, 401, 403, 404, 500]  # so you can see error bodies if any
      register: secret_resp

    - name: Show password item only (if present)
      vars:
        items_by_slug: >-
          {{ (secret_resp.json.items | default([]))
             | items2dict(key_name='slug', value_name='itemValue') }}
      debug:
        msg: "{{ items_by_slug.password | default('no password item found') }}"
